#!/bin/bash

echo "Install Dependencies"
echo "Install Generic Tools"
sudo apt -y install build-essential cmake pkg-config unzip yasm git checkinstall
sudo apt -y install build-essential
sudo apt -y install gcc-7 g++-7 gcc-8 g++-8 gcc-9 g++-9

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 7
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 7
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9

echo "Install Image I/O libs"
sudo -y apt install libjpeg-dev libpng-dev libtiff-dev

echo "Install Video and Audio libs"
sudo apt -y install libavcodec-dev libavformat-dev libswscale-dev libavresample-dev
sudo apt -y install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
sudo apt -y install libxvidcore-dev x264 libx264-dev libfaac-dev libmp3lame-dev libtheora-dev
sudo apt -y install libfaac-dev libmp3lame-dev libvorbis-dev

echo "Install OpenCore Speech Codec"
sudo apt -y install libopencore-amrnb-dev libopencore-amrwb-dev

echo "Install Camera Programmiong Interface Libs"
sudo apt-get install -y libdc1394-22 libdc1394-22-dev libxine2-dev libv4l-dev v4l-utils
cd /usr/include/linux
sudo ln -s -f ../libv4l1-videodev.h videodev.h
cd 

echo "Install GTK lib for GUI functionalities"
sudo apt-get install -y libgtk-3-dev

echo "Install Python Libs for Python3"
sudo apt-get install -y python3-dev python3-pip
sudo -H pip3 install -U pip numpy
sudo apt -y install python3-testresources

echo "Install Parallelism libs for C++"
sudo apt-get install -y libtbb-dev

echo "Install Optimization libs for OpenCV"
sudo apt-get install -y libatlas-base-dev gfortran

echo "Install Optional libs"
sudo apt-get install -y libprotobuf-dev protobuf-compiler
sudo apt-get install -y libgoogle-glog-dev libgflags-dev
sudo apt-get install -y libgphoto2-dev libeigen3-dev libhdf5-dev doxygen

echo "Download OpenCV"
cd
wget -O opencv.zip https://github.com/opencv/opencv/archive/4.2.0.zip
unzip -o opencv.zip
rm opencv.zip
wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.2.0.zip
unzip -o opencv_contrib.zip
rm opencv_contrib.zip

echo "Install OpenCV"
cd opencv-4.2.0
rm -r build
mkdir build
cd build

cmake -D CMAKE_BUILD_TYPE=RELEASE \
-D CMAKE_INSTALL_PREFIX=/usr/local \
-D INSTALL_PYTHON_EXAMPLES=ON \
-D INSTALL_C_EXAMPLES=ON \
-D WITH_TBB=ON \
-D BUILD_opencv_cudacodec=OFF \
-D ENABLE_FAST_MATH=1 \
-D CUDA_FAST_MATH=1 \
-D WITH_CUDA=ON \
-D WITH_CUBLAS=1 \
-D WITH_V4L=ON \
-D WITH_QT=OFF \
-D WITH_OPENGL=ON \
-D WITH_GSTREAMER=ON \
-D OPENCV_GENERATE_PKGCONFIG=ON \
-D OPENCV_PC_FILE_NAME=opencv.pc \
-D OPENCV_ENABLE_NONFREE=ON \
-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-4.2.0/modules \
-D BUILD_EXAMPLES=ON \
-D WITH_CUDNN=ON \
-D OPENCV_DNN_CUDA=ON \
-D CUDA_ARCH_BIN=7.5 \
-D CUDNN_LIBRARY=/usr/local/cuda/lib64/libcudnn.so.7.6.5 \
-D CUDNN_INCLUDE_DIR=/usr/local/cuda/include ..

make -j4
sudo make install
sudo ldconfig
